FROM python:3.11-slim

RUN pip install --upgrade pip

COPY requirements.txt .
RUN pip install -r requirements.txt

WORKDIR /app/ 

COPY ["inference.py", "data/input_data.json", ".env", "./"]

CMD ["python", "inference.py"]