FROM python:3.11-slim

RUN pip install --upgrade pip

COPY requirements.txt .
RUN pip install -r requirements.txt

WORKDIR /app/ 

COPY ["train.py", "data/", ".env", "./"]                

CMD ["python", "train.py"]